name: Build and push image

on:
  push:
    branches:
      - master

jobs:
  build_and_push_image:
    name: Build Docker image and push to registries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build_push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/arm64
          tags: |
            ghcr.io/brentoates/qbittorrent-port-forward-file-arm64:latest
            ghcr.io/brentoates/qbittorrent-port-forward-file-arm64:${{ github.sha }}

      - name: Image digest
        run: echo ${{ steps.docker_build_push.outputs.digest }}
